// examples/svelte/basic/src/lib/Posts.svelte
<script lang="ts">
  import { useQueryClient, createQuery } from '@tanstack/svelte-query'
  import { getPosts } from './data'

  const client = useQueryClient()

  let limit = 10

  const posts = createQuery<
    { id: number; title: string; body: string }[],
    Error
  >({
    queryKey: ['posts', limit],
    queryFn: () => getPosts(limit),
  })
</script>

<div>
  <div>
    {#if posts.status === 'pending'}
      <span>Loading...</span>
    {:else if posts.status === 'error'}
      <span>Error: {posts.error.message}</span>
    {:else}
      <ul>
        {#each posts.data as post}
          <article>
            <a
              href={`/${post.id}`}
              style={// We can use the queryCache here to show bold links for
              // ones that are cached
              client.getQueryData(['post', post.id])
                ? 'font-weight: bold; color: indianred'
                : 'cursor: pointer'}
            >
              {post.title}
            </a>
          </article>
        {/each}
      </ul>
      {#if posts.isFetching}
        <div style="color:darkgreen; font-weight:700">
          Background Updating...
        </div>
      {/if}
    {/if}
  </div>
</div>

<style>
  article {
    text-align: left;
  }
  a {
    display: block;
    color: white;
    font-size: 1.5rem;
    margin-bottom: 1rem;
  }
</style>

// examples/angular/router/src/app/components/posts.component.ts
import { ChangeDetectionStrategy, Component, inject } from '@angular/core'
import { RouterLink } from '@angular/router'
import { QueryClient, injectQuery } from '@tanstack/angular-query-experimental'
import { lastValueFrom } from 'rxjs'
import { PostsService } from '../services/posts-service'

@Component({
  changeDetection: ChangeDetectionStrategy.OnPush,
  selector: 'posts',
  templateUrl: './posts.component.html',
  imports: [RouterLink],
})
export default class PostsComponent {
  #postsService = inject(PostsService)

  postsQuery = injectQuery(() => ({
    queryKey: ['posts'],
    queryFn: () => lastValueFrom(this.#postsService.allPosts$()),
  }))

  queryClient = inject(QueryClient)
}

<div>
  <h1>Posts</h1>
  @switch (postsQuery.status()) {
    @case ('pending') {
      Loading...
    }
    @case ('error') {
      Error: {{ postsQuery.error()?.message }}
    }
    @default {
      <div class="todo-container">
        @for (post of postsQuery.data(); track post.id) {
          <p>
            <!--          We can access the query data here to show bold links for-->
            <!--          ones that are cached-->
            <a
              routerLink="post/{{ post.id }}"
              [style]="
                queryClient.getQueryData(['post', post.id])
                  ? {
                      fontWeight: 'bold',
                      color: 'green'
                    }
                  : {}
              "
              >{{ post.title }}</a
            >
          </p>
        }
      </div>
    }
  }
  <div>
    @if (postsQuery.isFetching()) {
      Background Updating...
    }
  </div>
</div>
