// packages/solid-query/src/isRestoring.ts
// based on react-query/src/isRestoring.tsx

import { createContext, useContext } from 'solid-js'

const isRestoring = () => false
const IsRestoringContext = createContext(isRestoring)

const useIsRestoring = () => useContext(IsRestoringContext)
const IsRestoringProvider = IsRestoringContext.Provider

export { IsRestoringContext, IsRestoringProvider, useIsRestoring }

// packages/react-query/snap/esm/isRestoring.js
import * as React from "react";
const IsRestoringContext = React.createContext(false);
const useIsRestoring = () => React.useContext(IsRestoringContext);
const IsRestoringProvider = IsRestoringContext.Provider;
export {
  IsRestoringProvider,
  useIsRestoring
};
//# sourceMappingURL=isRestoring.js.map
