// packages/angular-query-experimental/src/createMutation.ts
import {
  DestroyRef,
  assertInInjectionContext,
  computed,
  effect,
  inject,
  signal,
} from '@angular/core'
import { MutationObserver, notifyManager } from '@tanstack/query-core'
import { QueryClientService } from './QueryClientService'
import type { DefaultError, QueryClient } from '@tanstack/query-core'

import type {
  CreateMutateFunction,
  CreateMutationOptions,
  CreateMutationResult,
} from './types'

export function createMutation<
  TData = unknown,
  TError = DefaultError,
  TVariables = void,
  TContext = unknown,
>(
  options: () => CreateMutationOptions<TData, TError, TVariables, TContext>,
  queryClient?: QueryClient,
): CreateMutationResult<TData, TError, TVariables, TContext> {
  assertInInjectionContext(createMutation)
  if (!queryClient) {
    queryClient = inject(QueryClientService).useQueryClient()
  }

  const observer = new MutationObserver<TData, TError, TVariables, TContext>(
    queryClient,
    options(),
  )
  const mutate: CreateMutateFunction<TData, TError, TVariables, TContext> = (
    variables,
    mutateOptions,
  ) => {
    observer.mutate(variables, mutateOptions).catch(noop)
  }

  effect(() => {
    observer.setOptions(options())
  })

  const result = signal(observer.getCurrentResult())
  const unsubscribe = observer.subscribe(
    notifyManager.batchCalls((val) => {
      result.set(val)
    }),
  )
  const destroyRef = inject(DestroyRef)
  destroyRef.onDestroy(unsubscribe)

  return computed(() => ({
    ...result(),
    mutate,
    mutateAsync: result().mutate,
  }))
}

// eslint-disable-next-line @typescript-eslint/no-empty-function
function noop() {}

// packages/solid-query/src/createMutation.ts
import type { QueryClient, DefaultError } from '@tanstack/query-core'
import { MutationObserver } from '@tanstack/query-core'
import { useQueryClient } from './QueryClientProvider'
import type {
  CreateMutateFunction,
  CreateMutationOptions,
  CreateMutationResult,
} from './types'
import { createComputed, onCleanup, on } from 'solid-js'
import { createStore } from 'solid-js/store'
import { shouldThrowError } from './utils'

// HOOK
export function createMutation<
  TData = unknown,
  TError = DefaultError,
  TVariables = void,
  TContext = unknown,
>(
  options: CreateMutationOptions<TData, TError, TVariables, TContext>,
  queryClient?: () => QueryClient,
): CreateMutationResult<TData, TError, TVariables, TContext> {
  const client = useQueryClient(queryClient?.())

  const observer = new MutationObserver<TData, TError, TVariables, TContext>(
    client,
    options(),
  )

  const mutate: CreateMutateFunction<TData, TError, TVariables, TContext> = (
    variables,
    mutateOptions,
  ) => {
    observer.mutate(variables, mutateOptions).catch(noop)
  }

  const [state, setState] = createStore<
    CreateMutationResult<TData, TError, TVariables, TContext>
  >({
    ...observer.getCurrentResult(),
    mutate,
    mutateAsync: observer.getCurrentResult().mutate,
  })

  createComputed(() => {
    observer.setOptions(options())
  })

  createComputed(
    on(
      () => state.status,
      () => {
        if (
          state.isError &&
          shouldThrowError(observer.options.throwErrors, [state.error])
        ) {
          throw state.error
        }
      },
    ),
  )

  const unsubscribe = observer.subscribe((result) => {
    setState({
      ...result,
      mutate,
      mutateAsync: result.mutate,
    })
  })

  onCleanup(unsubscribe)

  return state
}

// eslint-disable-next-line @typescript-eslint/no-empty-function
function noop() {}
