// packages/angular-query-experimental/src/create-base-query.ts
import {
  DestroyRef,
  Injector,
  NgZone,
  computed,
  effect,
  inject,
  runInInjectionContext,
  signal,
  untracked,
} from '@angular/core'
import { QueryClient, notifyManager } from '@tanstack/query-core'
import { signalProxy } from './signal-proxy'
import { shouldThrowError } from './util'
import { lazyInit } from './util/lazy-init/lazy-init'
import { injectIsRestoring } from './inject-is-restoring'
import type {
  QueryKey,
  QueryObserver,
  QueryObserverResult,
} from '@tanstack/query-core'
import type { CreateBaseQueryOptions } from './types'

/**
 * Base implementation for `injectQuery` and `injectInfiniteQuery`.
 * @param optionsFn
 * @param Observer
 */
export function createBaseQuery<
  TQueryFnData,
  TError,
  TData,
  TQueryData,
  TQueryKey extends QueryKey,
>(
  optionsFn: () => CreateBaseQueryOptions<
    TQueryFnData,
    TError,
    TData,
    TQueryData,
    TQueryKey
  >,
  Observer: typeof QueryObserver,
) {
  const injector = inject(Injector)
  return lazyInit(() => {
    const ngZone = injector.get(NgZone)
    const destroyRef = injector.get(DestroyRef)
    const queryClient = injector.get(QueryClient)
    const isRestoring = injectIsRestoring(injector)

    /**
     * Signal that has the default options from query client applied
     * computed() is used so signals can be inserted into the options
     * making it reactive. Wrapping options in a function ensures embedded expressions
     * are preserved and can keep being applied after signal changes
     */
    const defaultedOptionsSignal = computed(() => {
      const options = runInInjectionContext(injector, () => optionsFn())
      const defaultedOptions = queryClient.defaultQueryOptions(options)
      defaultedOptions._optimisticResults = isRestoring()
        ? 'isRestoring'
        : 'optimistic'
      return defaultedOptions
    })

    const observer = new Observer<
      TQueryFnData,
      TError,
      TData,
      TQueryData,
      TQueryKey
    >(queryClient, defaultedOptionsSignal())

    const resultSignal = signal(
      observer.getOptimisticResult(defaultedOptionsSignal()),
    )

    effect(
      () => {
        const defaultedOptions = defaultedOptionsSignal()
        observer.setOptions(defaultedOptions, {
          // Do not notify on updates because of changes in the options because
          // these changes should already be reflected in the optimistic result.
          listeners: false,
        })
        untracked(() => {
          resultSignal.set(observer.getOptimisticResult(defaultedOptions))
        })
      },
      {
        injector,
      },
    )

    effect(
      () => {
        const _isRestoring = isRestoring()

        untracked(() => {
          const unsubscribe = _isRestoring
            ? () => undefined
            : ngZone.runOutsideAngular(() =>
                // observer.trackResult is not used as this optimization is not needed for Angular
                observer.subscribe(
                  notifyManager.batchCalls(
                    (state: QueryObserverResult<TData, TError>) => {
                      ngZone.run(() => {
                        if (
                          state.isError &&
                          !state.isFetching &&
                          shouldThrowError(observer.options.throwOnError, [
                            state.error,
                            observer.getCurrentQuery(),
                          ])
                        ) {
                          throw state.error
                        }
                        resultSignal.set(state)
                      })
                    },
                  ),
                ),
              )
          destroyRef.onDestroy(unsubscribe)
        })
      },
      {
        injector,
      },
    )

    return signalProxy(resultSignal)
  })
}

// packages/solid-query/src/createBaseQuery.ts
import { QueryObserver } from '@tanstack/query-core'
import type { QueryKey, QueryObserverResult } from '@tanstack/query-core'
import { CreateBaseQueryOptions } from './types'
import { useQueryClient } from './QueryClientProvider'
import {
  onMount,
  onCleanup,
  createComputed,
  createResource,
} from 'solid-js'
import { createStore } from 'solid-js/store'

// Base Query Function that is used to create the query.
export function createBaseQuery<
  TQueryFnData,
  TError,
  TData,
  TQueryData,
  TQueryKey extends QueryKey,
>(
  options: CreateBaseQueryOptions<
    TQueryFnData,
    TError,
    TData,
    TQueryData,
    TQueryKey
  >,
  Observer: typeof QueryObserver,
): QueryObserverResult<TData, TError> {
  const queryClient = useQueryClient()

  const defaultedOptions = queryClient.defaultQueryOptions(options)
  defaultedOptions._optimisticResults = 'optimistic'
  const observer = new Observer(queryClient, defaultedOptions)

  const [state, setState] = createStore<QueryObserverResult<TData, TError>>(
    // @ts-ignore
    observer.getOptimisticResult(defaultedOptions),
  )

  const [dataResource, { refetch }] = createResource<TData | undefined>(() => {
    return new Promise((resolve) => {
      if (state.isSuccess) resolve(state.data)
      if (state.isError && !state.isFetching) {
        throw state.error
      }
    })
  })

  const unsubscribe = observer.subscribe((result) => {
    setState(result)
    refetch()
  })

  onCleanup(() => unsubscribe())

  onMount(() => {
    observer.setOptions(defaultedOptions, { listeners: false })
  })

  createComputed(() => {
    const newDefaultedOptions = queryClient.defaultQueryOptions(options)
    observer.setOptions(newDefaultedOptions)
  })

  const handler = {
    get(
      target: QueryObserverResult<TData, TError>,
      prop: keyof QueryObserverResult<TData, TError>,
    ): any {
      if (prop === 'data') {
        if (state.isLoading) {
          return dataResource()
        }
        return state.data
      }
      return Reflect.get(target, prop)
    },
  }

  return new Proxy(state, handler) as QueryObserverResult<TData, TError>
}
