// packages/react-query-persist-client/src/BroadcastQueryClientProvider.tsx
'use client'
import * as React from 'react'

import { broadcastQueryClientRestore } from '@tanstack/query-broadcast-client-experimental'
import {
  IsRestoringProvider,
  QueryClientProvider,
  useIsRestoring,
} from '@tanstack/react-query'
import type { BroadcastQueryClientRestoreOptions } from '@tanstack/query-broadcast-client-experimental'
import type { OmitKeyof, QueryClientProviderProps } from '@tanstack/react-query'

export type BroadcastQueryClientProviderProps = QueryClientProviderProps & {
  broadcastOptions: OmitKeyof<BroadcastQueryClientRestoreOptions, 'queryClient'>
}

export const BroadcastQueryClientProvider = ({
  children,
  broadcastOptions,
  ...props
}: BroadcastQueryClientProviderProps): React.JSX.Element => {
  const parentIsRestoring = useIsRestoring()
  const [isRestoring, setIsRestoring] = React.useState(true)
  const optionsRef = React.useRef(broadcastOptions)

  React.useEffect(() => {
    optionsRef.current = broadcastOptions
  })

  React.useEffect(() => {
    setIsRestoring(true)
    let mounted = true
    const [cleanup, restorePromise] = broadcastQueryClientRestore({
      ...optionsRef.current,
      queryClient: props.client,
    })

    restorePromise.then(() => {
      if (mounted) {
        setIsRestoring(false)
      }
    })

    return () => {
      mounted = false
      cleanup()
    }
  }, [props.client])

  return (
    <QueryClientProvider {...props}>
      <IsRestoringProvider value={parentIsRestoring || isRestoring}>
        {children}
      </IsRestoringProvider>
    </QueryClientProvider>
  )
}

// packages/solid-query-persist-client/src/BroadcastQueryClientProvider.tsx
import { broadcastQueryClientRestore } from '@tanstack/query-broadcast-client-experimental'
import {
  IsRestoringProvider,
  QueryClientProvider,
  useIsRestoring,
} from '@tanstack/solid-query'
import { createEffect, createMemo, createSignal, onCleanup } from 'solid-js'
import type { BroadcastQueryClientRestoreOptions } from '@tanstack/query-broadcast-client-experimental'
import type { JSX } from 'solid-js'
import type { QueryClientProviderProps } from '@tanstack/solid-query'

export type BroadcastQueryClientProviderProps = QueryClientProviderProps & {
  broadcastOptions: Omit<BroadcastQueryClientRestoreOptions, 'queryClient'>
}

export const BroadcastQueryClientProvider = (
  props: BroadcastQueryClientProviderProps,
): JSX.Element => {
  const parentIsRestoring = useIsRestoring()
  const [isRestoring, setIsRestoring] = createSignal(true)

  const options = createMemo(() => ({
    ...props.broadcastOptions,
    queryClient: props.client,
  }))

  createEffect(() => {
    setIsRestoring(true)
    let mounted = true
    const [cleanup, restorePromise] = broadcastQueryClientRestore(options())

    restorePromise.then(() => {
      if (mounted) {
        setIsRestoring(false)
      }
    })

    onCleanup(() => {
      mounted = false
      cleanup()
    })
  })

  return (
    <QueryClientProvider client={props.client}>
      <IsRestoringProvider value={() => parentIsRestoring() || isRestoring()}>
        {props.children}
      </IsRestoringProvider>
    </QueryClientProvider>
  )
}
