// packages/preact-query-persist-client/src/PersistQueryClientProvider.tsx
import { useEffect, useRef, useState } from 'preact/hooks'
import type { VNode } from 'preact'

import {
  persistQueryClientRestore,
  persistQueryClientSubscribe,
} from '@tanstack/query-persist-client-core'
import {
  IsRestoringProvider,
  QueryClientProvider,
} from '@tanstack/preact-query'
import type { PersistQueryClientOptions } from '@tanstack/query-persist-client-core'
import type {
  OmitKeyof,
  QueryClientProviderProps,
} from '@tanstack/preact-query'

/**
 * The props of `PersistQueryClientProvider`: the props of `QueryClientProvider`, plus the
 * `persistOptions` and callbacks for when restoring succeeds or fails.
 */
export type PersistQueryClientProviderProps = QueryClientProviderProps & {
  persistOptions: OmitKeyof<PersistQueryClientOptions, 'queryClient'>
  onSuccess?: () => Promise<unknown> | unknown
  onError?: () => Promise<unknown> | unknown
}

/**
 * Provides the `QueryClient` like `QueryClientProvider`, and restores the persisted client first:
 * while restoring, `useIsRestoring` returns `true` and queries wait for the restore to finish
 * before subscribing. Once restored, the client is saved with the persister whenever the cache
 * changes.
 * @param props - The `QueryClientProvider` props, the `persistOptions`, and the `onSuccess` and
 * `onError` callbacks. `onSuccess` is called once restoring finishes, even if nothing was restored
 * (e.g. because the persisted client expired), and `onError` if restoring or `onSuccess` throws.
 * @returns The `QueryClientProvider` wrapping the children.
 */
export const PersistQueryClientProvider = ({
  children,
  persistOptions,
  onSuccess,
  onError,
  ...props
}: PersistQueryClientProviderProps): VNode => {
  const [isRestoring, setIsRestoring] = useState(true)
  const optionsRef = useRef({ persistOptions, onSuccess, onError })
  const didRestoreRef = useRef(false)

  useEffect(() => {
    optionsRef.current = { persistOptions, onSuccess, onError }
  })

  useEffect(() => {
    const options = {
      ...optionsRef.current.persistOptions,
      queryClient: props.client,
    }
    if (!didRestoreRef.current) {
      didRestoreRef.current = true
      persistQueryClientRestore(options)
        .then(() => optionsRef.current.onSuccess?.())
        .catch(() => optionsRef.current.onError?.())
        .finally(() => {
          setIsRestoring(false)
        })
    }
    return isRestoring ? undefined : persistQueryClientSubscribe(options)
  }, [props.client, isRestoring])

  return (
    <QueryClientProvider {...props}>
      <IsRestoringProvider value={isRestoring}>{children}</IsRestoringProvider>
    </QueryClientProvider>
  )
}

// packages/solid-query-persist-client/src/PersistQueryClientProvider.tsx
import {
  persistQueryClientRestore,
  persistQueryClientSubscribe,
} from '@tanstack/query-persist-client-core'
import { createEffect, createMemo, createSignal, onCleanup } from 'solid-js'
import { IsRestoringProvider, QueryClientProvider } from '@tanstack/solid-query'
import type { PersistQueryClientOptions } from '@tanstack/query-persist-client-core'
import type { OmitKeyof, QueryClientProviderProps } from '@tanstack/solid-query'
import type { JSX } from 'solid-js'

/**
 * The props of `PersistQueryClientProvider`: the props of `QueryClientProvider`, plus the
 * `persistOptions` and callbacks for when restoring succeeds or fails.
 */
export type PersistQueryClientProviderProps = QueryClientProviderProps & {
  persistOptions: OmitKeyof<PersistQueryClientOptions, 'queryClient'>
  onSuccess?: () => void
  onError?: () => void
}

/**
 * Provides the `QueryClient` like `QueryClientProvider`, and restores the persisted client first:
 * while restoring, `useIsRestoring` returns `true` and queries wait for the restore to finish
 * before subscribing. Once restored, the client is saved with the persister whenever the cache
 * changes.
 * @param props - The `QueryClientProvider` props, the `persistOptions`, and the `onSuccess` and
 * `onError` callbacks. `onSuccess` is called once restoring finishes, even if nothing was restored
 * (e.g. because the persisted client expired), and `onError` if restoring or `onSuccess` throws.
 * @returns The `QueryClientProvider` wrapping the children.
 */
export const PersistQueryClientProvider = (
  props: PersistQueryClientProviderProps,
): JSX.Element => {
  const [isRestoring, setIsRestoring] = createSignal(true)

  const options = createMemo(() => ({
    ...props.persistOptions,
    queryClient: props.client,
  }))

  createEffect(() => {
    setIsRestoring(true)
    persistQueryClientRestore(options())
      .then(() => props.onSuccess?.())
      .catch(() => props.onError?.())
      .finally(() => {
        setIsRestoring(false)
      })
  })

  createEffect(() => {
    let unsubscribe = () => {}
    if (!isRestoring()) {
      unsubscribe = persistQueryClientSubscribe(options())
    }
    onCleanup(() => unsubscribe())
  })

  return (
    <QueryClientProvider client={props.client}>
      <IsRestoringProvider value={isRestoring}>
        {props.children}
      </IsRestoringProvider>
    </QueryClientProvider>
  )
}
