// examples/svelte/basic/src/lib/Post.svelte
<script lang="ts">
import { createQuery } from '@tanstack/svelte-query'
import { getPostById } from './data'
import type { Post } from './types'

export let postId: number

const post = createQuery<Post>({
  queryKey: ['post', postId],
  queryFn: () => getPostById(postId),
})
</script>

<div>
  <div>
    <a class="button" href="/"> Back </a>
  </div>
  {#if !postId || $post.isPending}
    <span>Loading...</span>
  {/if}
  {#if $post.error}
    <span>Error: {$post.error.message}</span>
  {/if}
  {#if $post.isSuccess}
    <h1>{$post.data.title}</h1>
    <div>
      <p>{$post.data.body}</p>
    </div>
    <div>{$post.isFetching ? 'Background Updating...' : ' '}</div>
  {/if}
</div>

// examples/angular/query-options-from-a-service/src/app/components/post.component.ts
import {
  ChangeDetectionStrategy,
  Component,
  inject,
  input,
  numberAttribute,
} from '@angular/core'
import { RouterLink } from '@angular/router'
import { injectQuery } from '@tanstack/angular-query'
import { QueriesService } from '../services/queries-service'

@Component({
  changeDetection: ChangeDetectionStrategy.OnPush,
  selector: 'post',
  templateUrl: './post.component.html',
  imports: [RouterLink],
})
export default class PostComponent {
  private queries = inject(QueriesService)

  postId = input.required({
    transform: numberAttribute,
  })

  postQuery = injectQuery(() => this.queries.post(this.postId()))
}

<div>
  <div>
    <a routerLink="/" href="#">Back</a>
  </div>
  @if (postQuery.isPending()) {
    Loading...
  } @else if (postQuery.isError()) {
    Error: {{ postQuery.error().message }}
  }
  @if (postQuery.isSuccess()) {
    @let post = postQuery.data();
    <h1>{{ post.title }}</h1>
    <div>
      <p>{{ post.body }}</p>
    </div>
    @if (postQuery.isFetching()) {
      Background Updating...
    }
  }
</div>
