// integrations/react-vite5/src/App.jsx
import { useQuery } from '@tanstack/react-query'

const App = () => {
  const query = useQuery({
    queryKey: ['test'],
    queryFn: async () => {
      await new Promise((r) => setTimeout(r, 1000))
      return 'Success'
    },
  })

  if (query.isPending) {
    return <div>Loading...</div>
  }

  if (query.isError) {
    return <div>An error has occurred!</div>
  }

  return <div>{query.data}</div>
}

export default App

// integrations/angular-cli-20/src/app/app.ts
import { Component } from '@angular/core'
import { injectQuery } from '@tanstack/angular-query'

@Component({
  selector: 'app-root',
  template: `
    @if (query.isPending()) {
      <div>Loading...</div>
    }
    @if (query.isError()) {
      <div>An error has occurred!</div>
    }
    @if (query.isSuccess()) {
      <div>{{ query.data() }}</div>
    }
  `,
})
export class App {
  query = injectQuery(() => ({
    queryKey: ['test'],
    queryFn: async () => {
      await new Promise((r) => setTimeout(r, 1000))
      return 'Success'
    },
  }))
}
