// integrations/react-webpack-5/src/index.js
import React from 'react'
import ReactDOM from 'react-dom/client'
import { QueryClient, QueryClientProvider } from '@tanstack/react-query'
import { ReactQueryDevtools } from '@tanstack/react-query-devtools'
import App from './App'

const queryClient = new QueryClient()

const root = ReactDOM.createRoot(document.getElementById('root'))

root.render(
  <React.StrictMode>
    <QueryClientProvider client={queryClient}>
      <App />
      <ReactQueryDevtools />
    </QueryClientProvider>
  </React.StrictMode>,
)

// integrations/solid-vite/src/index.jsx
/* @refresh reload */
import { render } from 'solid-js/web'
import { QueryClient, QueryClientProvider } from '@tanstack/solid-query'
import { SolidQueryDevtools } from '@tanstack/solid-query-devtools'
import App from './App'

const queryClient = new QueryClient()

const root = document.getElementById('root')

render(
  () => (
    <QueryClientProvider client={queryClient}>
      <SolidQueryDevtools />
      <App />
    </QueryClientProvider>
  ),
  root,
)
