// integrations/vue-vite/src/App.vue
<script setup lang="ts">
import { useQuery } from '@tanstack/vue-query'

const { isPending, isError, data } = useQuery({
  queryKey: ['test'],
  queryFn: async () => {
    await new Promise((r) => setTimeout(r, 1000))
    return 'Success'
  },
})
</script>

<template>
  <div v-if="isPending">Loading...</div>
  <div v-else-if="isError">An error has occurred!</div>
  <div v-else-if="data">{{ data }}</div>
</template>

// integrations/react-webpack-5/src/App.js
import React from 'react'
import { useQuery } from '@tanstack/react-query'

const App = () => {
  const query = useQuery({
    queryKey: ['test'],
    queryFn: async () => {
      await new Promise((r) => setTimeout(r, 1000))
      return 'Success'
    },
  })

  if (query.isPending) {
    return <div>Loading...</div>
  }

  if (query.isError) {
    return <div>An error has occurred!</div>
  }

  return <div>{query.data}</div>
}

export default App
