// packages/svelte-query-devtools/src/Devtools.svelte
<script lang="ts">
  import { onMount } from 'svelte'
  import { BROWSER, DEV } from 'esm-env'
  import { onlineManager, useQueryClient } from '@tanstack/svelte-query'
  import type { QueryClient } from '@tanstack/svelte-query'
  import type {
    DevtoolsButtonPosition,
    DevtoolsErrorType,
    DevtoolsPosition,
    TanstackQueryDevtools,
  } from '@tanstack/query-devtools'

  export let initialIsOpen = false
  export let buttonPosition: DevtoolsButtonPosition = 'bottom-right'
  export let position: DevtoolsPosition = 'bottom'
  export let client: QueryClient = useQueryClient()
  export let errorTypes: Array<DevtoolsErrorType> = []
  export let styleNonce: string | undefined = undefined
  export let shadowDOMTarget: ShadowRoot | undefined = undefined
  export let hideDisabled: boolean = false

  let ref: HTMLDivElement
  let devtools: TanstackQueryDevtools | undefined

  if (DEV && BROWSER) {
    onMount(() => {
      import('@tanstack/query-devtools').then((m) => {
        const QueryDevtools = m.TanstackQueryDevtools

        devtools = new QueryDevtools({
          client,
          queryFlavor: 'Svelte Query',
          version: '5',
          onlineManager,
          buttonPosition,
          position,
          initialIsOpen,
          errorTypes,
          styleNonce,
          shadowDOMTarget,
          hideDisabled,
        })

        devtools.mount(ref)
      })

      return () => {
        devtools?.unmount()
      }
    })
  }

  $: {
    if (devtools) {
      devtools.setButtonPosition(buttonPosition)
      devtools.setPosition(position)
      devtools.setInitialIsOpen(initialIsOpen)
      devtools.setErrorTypes(errorTypes)
    }
  }
</script>

<div class="tsqd-parent-container" bind:this={ref}></div>

// packages/vue-query-devtools/src/devtools.vue
<script setup lang="ts">
import { onMounted, onScopeDispose, ref, watchEffect } from 'vue'
import { onlineManager, useQueryClient } from '@tanstack/vue-query'
import { TanstackQueryDevtools } from '@tanstack/query-devtools'
import type { DevtoolsOptions } from './types'

const props = defineProps<DevtoolsOptions>()

const div = ref<HTMLElement>()
const client = props.client || useQueryClient()
const devtools = new TanstackQueryDevtools({
  client,
  queryFlavor: 'Vue Query',
  version: '5',
  onlineManager,
  buttonPosition: props.buttonPosition,
  position: props.position,
  initialIsOpen: props.initialIsOpen,
  errorTypes: props.errorTypes,
  styleNonce: props.styleNonce,
  shadowDOMTarget: props.shadowDOMTarget,
  hideDisabled: props.hideDisabled,
})

watchEffect(() => {
  devtools.setButtonPosition(props.buttonPosition || 'bottom-right')
  devtools.setPosition(props.position || 'bottom')
  devtools.setInitialIsOpen(props.initialIsOpen)
  devtools.setErrorTypes(props.errorTypes || [])
})

onMounted(() => {
  devtools.mount(div.value as HTMLElement)
})

onScopeDispose(() => {
  devtools.unmount()
})
</script>

<template>
  <div className="tsqd-parent-container" ref="div"></div>
</template>
