// examples/react/star-wars/src/Characters.tsx
import { Link as RouterLink } from 'react-router-dom'
import { useQuery } from '@tanstack/react-query'
import { getCharacters } from './api'

export default function Characters() {
  const { status, data } = useQuery({
    queryKey: ['characters'],
    queryFn: () => getCharacters(),
  })

  if (status === 'pending') return <p>Loading...</p>
  if (status === 'error') return <p>Error :(</p>

  return (
    <div>
      <h2 className="text-4xl">Characters</h2>
      {data.results.map((person: any) => {
        const personUrlParts = person.url.split('/').filter(Boolean)
        const personId = personUrlParts[personUrlParts.length - 1]
        return (
          <article key={personId}>
            <RouterLink
              className="text-blue-500 hover:underline"
              to={`/characters/${personId}`}
            >
              <h6 className="text-xl">{person.name}</h6>
            </RouterLink>
          </article>
        )
      })}
    </div>
  )
}

// examples/svelte/star-wars/src/routes/characters/+page.svelte
<script lang="ts">
  import { createQuery } from '@tanstack/svelte-query'
  import { getCharacters } from '$lib/api'

  const query = createQuery(() => ({
    queryKey: ['characters'],
    queryFn: () => getCharacters(),
  }))
</script>

{#if query.status === 'pending'}
  <p>Loading...</p>
{/if}

{#if query.status === 'error'}
  <p>Error :(</p>
{/if}

{#if query.status === 'success'}
  <div>
    <h2 class="text-4xl">Characters</h2>
    {#each query.data.results as person}
      {@const personUrlParts = person.url.split('/').filter(Boolean)}
      {@const personId = personUrlParts[personUrlParts.length - 1]}
      <article>
        <a
          class="text-blue-500 hover:underline"
          href={`/characters/${personId}`}
        >
          <h6 class="text-xl">{person.name}</h6>
        </a>
      </article>
    {/each}
  </div>
{/if}
