// packages/react-query/src/useMutationState.ts
'use client'
import * as React from 'react'

import { notifyManager, replaceEqualDeep } from '@tanstack/query-core'
import { useQueryClient } from './QueryClientProvider'
import type {
  Mutation,
  MutationCache,
  MutationFilters,
  MutationState,
  QueryClient,
} from '@tanstack/query-core'

export function useIsMutating(
  filters?: MutationFilters,
  queryClient?: QueryClient,
): number {
  const client = useQueryClient(queryClient)
  return useMutationState(
    { filters: { ...filters, status: 'pending' } },
    client,
  ).length
}

type MutationTypeFromResult<TResult> = [TResult] extends [
  MutationState<
    infer TData,
    infer TError,
    infer TVariables,
    infer TOnMutateResult
  >,
]
  ? Mutation<TData, TError, TVariables, TOnMutateResult>
  : Mutation

type MutationStateOptions<
  TResult = MutationState,
  TMutation extends Mutation<any, any, any, any> =
    MutationTypeFromResult<TResult>,
> = {
  filters?: MutationFilters
  select?: (mutation: TMutation) => TResult
}

function getResult<
  TResult = MutationState,
  TMutation extends Mutation<any, any, any, any> =
    MutationTypeFromResult<TResult>,
>(
  mutationCache: MutationCache,
  options: MutationStateOptions<TResult, TMutation>,
): Array<TResult> {
  return mutationCache
    .findAll(options.filters)
    .map(
      (mutation): TResult =>
        (options.select
          ? options.select(mutation as TMutation)
          : mutation.state) as TResult,
    )
}

/**
 * @template TResult - The type of values returned by the `select` callback.
 * @template TMutation - Narrows the type of the `mutation` argument passed to
 * `select`. This is a caller-side assertion — the mutation cache stores
 * mutations as the base `Mutation` type, so it is the caller's responsibility
 * to ensure `TMutation` matches the actual mutations in the cache (e.g. by
 * specifying a `mutationKey` in `filters`).
 */
export function useMutationState<
  TResult = MutationState,
  TMutation extends Mutation<any, any, any, any> =
    MutationTypeFromResult<TResult>,
>(
  options: MutationStateOptions<TResult, TMutation> = {},
  queryClient?: QueryClient,
): Array<TResult> {
  const mutationCache = useQueryClient(queryClient).getMutationCache()
  const optionsRef = React.useRef(options)
  const result = React.useRef<Array<TResult>>(null)
  if (result.current === null) {
    result.current = getResult(mutationCache, options)
  }

  React.useEffect(() => {
    optionsRef.current = options
  })

  return React.useSyncExternalStore(
    React.useCallback(
      (onStoreChange) =>
        mutationCache.subscribe(() => {
          const nextResult = replaceEqualDeep(
            result.current,
            getResult(mutationCache, optionsRef.current),
          )
          if (result.current !== nextResult) {
            result.current = nextResult
            notifyManager.schedule(onStoreChange)
          }
        }),
      [mutationCache],
    ),
    () => result.current,
    () => result.current,
  )!
}

// packages/lit-query/src/useMutationState.ts
import {
  replaceEqualDeep,
  type Mutation,
  type MutationFilters,
  type MutationState,
  type QueryClient,
} from '@tanstack/query-core'
import type { ReactiveControllerHost } from 'lit'
import {
  createValueAccessor,
  readAccessor,
  type Accessor,
  type ValueAccessor,
} from './accessor.js'
import { BaseController } from './controllers/BaseController.js'

type MutationTypeFromResult<TResult> = [TResult] extends [
  MutationState<
    infer TData,
    infer TError,
    infer TVariables,
    infer TOnMutateResult
  >,
]
  ? Mutation<TData, TError, TVariables, TOnMutateResult>
  : Mutation

/**
 * Options accepted by `useMutationState`.
 */
export type MutationStateOptions<
  TResult,
  TMutation extends Mutation<any, any, any, any> =
    MutationTypeFromResult<TResult>,
> = {
  /** Filters used to select mutations from the mutation cache. */
  filters?: Accessor<MutationFilters>
  /** Maps each matching mutation to the value returned by the accessor. */
  select?: (mutation: TMutation) => TResult
}

/**
 * Accessor returned by `useMutationState`.
 *
 * Call the accessor or read its `current` property to get the selected state for
 * matching mutations.
 */
export type MutationStateAccessor<TResult> = ValueAccessor<TResult[]> & {
  /** Removes the controller from its Lit host and unsubscribes observers. */
  destroy: () => void
}

class MutationStateController<
  TResult,
  TMutation extends Mutation<any, any, any, any> = MutationTypeFromResult<TResult>,
> extends BaseController<TResult[]> {
  private queryClient: QueryClient | undefined
  private unsubscribe: (() => void) | undefined

  constructor(
    host: ReactiveControllerHost,
    private readonly options: MutationStateOptions<TResult, TMutation>,
    queryClient?: QueryClient,
  ) {
    super(host, [], queryClient)

    if (!queryClient) {
      return
    }

    this.queryClient = queryClient
    this.result = this.computeState()
  }

  protected onConnected(): void {
    if (!this.syncClient()) {
      this.setMutationState([])
      return
    }

    this.subscribe()
    this.setMutationState(this.computeState())
  }

  protected onDisconnected(): void {
    this.unsubscribe?.()
    this.unsubscribe = undefined
    this.syncClient()
  }

  protected onHostUpdate(): void {
    if (!this.shouldRefreshOnHostUpdate()) {
      return
    }

    this.setMutationState(this.syncClient() ? this.computeState() : [])
  }

  protected onQueryClientChanged(): void {
    if (!this.syncClient()) {
      this.setMutationState([])
      return
    }

    if (this.connectedState) {
      this.subscribe()
      this.setMutationState(this.computeState())
    }
  }

  private syncClient(): boolean {
    const nextClient = this.tryGetQueryClient()
    if (!nextClient) {
      this.unsubscribe?.()
      this.unsubscribe = undefined
      this.queryClient = undefined
      return false
    }

    if (nextClient === this.queryClient) {
      return true
    }

    this.unsubscribe?.()
    this.unsubscribe = undefined
    this.queryClient = nextClient
    return true
  }

  private subscribe(): void {
    if (!this.queryClient) {
      return
    }

    if (this.unsubscribe) {
      return
    }

    this.unsubscribe = this.queryClient.getMutationCache().subscribe(() => {
      this.setMutationState(this.computeState())
    })
  }

  private setMutationState(next: TResult[]): void {
    this.setResult(replaceEqualDeep(this.result, next))
  }

  private shouldRefreshOnHostUpdate(): boolean {
    return (
      typeof this.options.filters === 'function' ||
      typeof this.options.select === 'function'
    )
  }

  private computeState(): TResult[] {
    if (!this.queryClient) {
      return []
    }

    const filters = this.options.filters
      ? readAccessor(this.options.filters)
      : undefined

    const select = this.options.select
    const mutations = this.queryClient.getMutationCache().findAll(filters)

    return mutations.map((mutation) => {
      if (select) {
        return select(mutation as TMutation)
      }

      return mutation.state as TResult
    })
  }
}

/**
 * Creates a Lit reactive controller that selects state from matching mutations
 * in the mutation cache.
 *
 * When `options.filters` is a function, it is re-read during host updates so
 * the selection can follow reactive host state. If `queryClient` is omitted,
 * the controller resolves the client from the nearest connected
 * `QueryClientProvider`.
 *
 * @param host - The Lit reactive controller host that owns the mutation cache
 * subscription.
 * @param options - Mutation state filters and optional selector.
 * @param queryClient - Optional explicit query client. Provide this for
 * controllers that should not resolve a client from Lit context.
 * @returns An accessor for the selected mutation state array.
 *
 * @example
 * ```ts
 * import { LitElement, html } from 'lit'
 * import { useMutationState } from '@tanstack/lit-query'
 *
 * class PendingUploads extends LitElement {
 *   private readonly uploads = useMutationState(this, {
 *     filters: { mutationKey: ['upload'], status: 'pending' },
 *     select: (mutation) => mutation.state.variables as File,
 *   })
 *
 *   render() {
 *     return html`<span>${this.uploads().length} uploads pending</span>`
 *   }
 * }
 * ```
 */
/**
 * @template TResult - The type of values returned by the `select` callback.
 * @template TMutation - Narrows the type of the `mutation` argument passed to
 * `select`. This is a caller-side assertion — the mutation cache stores
 * mutations as the base `Mutation` type, so it is the caller's responsibility
 * to ensure `TMutation` matches the actual mutations in the cache (e.g. by
 * specifying a `mutationKey` in `filters`).
 */
export function useMutationState<
  TResult = MutationState<unknown, unknown, unknown, unknown>,
  TMutation extends Mutation<any, any, any, any> = MutationTypeFromResult<TResult>,
>(
  host: ReactiveControllerHost,
  options: MutationStateOptions<TResult, TMutation> = {},
  queryClient?: QueryClient,
): MutationStateAccessor<TResult> {
  const controller = new MutationStateController<TResult, TMutation>(host, options, queryClient)
  return Object.assign(
    createValueAccessor(() => controller.current),
    {
      destroy: () => controller.destroy(),
    },
  )
}
