// packages/solid-query-persist-client/src/BroadcastQueryClientProvider.tsx
import { broadcastQueryClientRestore } from '@tanstack/query-broadcast-client-experimental'
import {
  IsRestoringProvider,
  QueryClientProvider,
  useIsRestoring,
} from '@tanstack/solid-query'
import { createEffect, createMemo, createSignal, onCleanup } from 'solid-js'
import type { BroadcastQueryClientRestoreOptions } from '@tanstack/query-broadcast-client-experimental'
import type { JSX } from 'solid-js'
import type { QueryClientProviderProps } from '@tanstack/solid-query'

export type BroadcastQueryClientProviderProps = QueryClientProviderProps & {
  broadcastOptions: Omit<BroadcastQueryClientRestoreOptions, 'queryClient'>
}

export const BroadcastQueryClientProvider = (
  props: BroadcastQueryClientProviderProps,
): JSX.Element => {
  const parentIsRestoring = useIsRestoring()
  const [isRestoring, setIsRestoring] = createSignal(true)

  const options = createMemo(() => ({
    ...props.broadcastOptions,
    queryClient: props.client,
  }))

  createEffect(() => {
    setIsRestoring(true)
    let mounted = true
    const [cleanup, restorePromise] = broadcastQueryClientRestore(options())

    restorePromise.then(() => {
      if (mounted) {
        setIsRestoring(false)
      }
    })

    onCleanup(() => {
      mounted = false
      cleanup()
    })
  })

  return (
    <QueryClientProvider client={props.client}>
      <IsRestoringProvider value={() => parentIsRestoring() || isRestoring()}>
        {props.children}
      </IsRestoringProvider>
    </QueryClientProvider>
  )
}

// packages/svelte-query-persist-client/src/BroadcastQueryClientProvider.svelte
<script lang="ts">
  import { broadcastQueryClientRestore } from '@tanstack/query-broadcast-client-experimental'
  import {
    QueryClientProvider,
    getIsRestoringContext,
    setIsRestoringContext,
  } from '@tanstack/svelte-query'
  import { box } from './utils.svelte.js'
  import type { BroadcastQueryClientRestoreOptions } from '@tanstack/query-broadcast-client-experimental'
  import type { QueryClientProviderProps } from '@tanstack/svelte-query'

  type BroadcastQueryClientProviderProps = QueryClientProviderProps & {
    broadcastOptions: Omit<BroadcastQueryClientRestoreOptions, 'queryClient'>
  }

  let {
    client,
    children,
    broadcastOptions,
    ...props
  }: BroadcastQueryClientProviderProps = $props()

  const parentIsRestoring = getIsRestoringContext()
  const isRestoring = box(true)

  setIsRestoringContext({
    get current() {
      return parentIsRestoring.current || isRestoring.current
    },
  })

  const options = $derived({
    ...broadcastOptions,
    queryClient: client,
  })

  $effect(() => {
    isRestoring.current = true
    const [cleanup, restorePromise] = broadcastQueryClientRestore(options)
    let mounted = true

    restorePromise.then(() => {
      if (mounted) {
        isRestoring.current = false
      }
    })

    return () => {
      mounted = false
      cleanup()
    }
  })
</script>

<QueryClientProvider {client} {...props}>
  {@render children?.()}
</QueryClientProvider>
