// integrations/solid-vite/src/index.jsx
/* @refresh reload */
import { render } from '@solidjs/web'
import { QueryClient, QueryClientProvider } from '@tanstack/solid-query'
import { SolidQueryDevtools } from '@tanstack/solid-query-devtools'
import App from './App'

const queryClient = new QueryClient()

const root = document.getElementById('root')

render(
  () => (
    <QueryClientProvider client={queryClient}>
      <SolidQueryDevtools />
      <App />
    </QueryClientProvider>
  ),
  root,
)

// examples/solid/offline/src/index.tsx
/* @refresh reload */
import { render } from 'solid-js/web'
import App from './App'
import { worker } from './api'

worker.start()

const root = document.getElementById('root')
if (!root) throw new Error('Missing #root element')

render(
  () => (
    <div style={{ padding: '16px' }}>
      <App />
    </div>
  ),
  root,
)
