// packages/solid-query/src/QueryErrorResetBoundary.tsx
// CONTEXT

import { createContext, createSignal, useContext, JSX } from 'solid-js'

interface QueryErrorResetBoundaryValue {
  clearReset: () => void
  isReset: () => boolean
  reset: () => void
}

function createValue(): QueryErrorResetBoundaryValue {
  const [isReset, setIsReset] = createSignal(false)
  return {
    clearReset: () => {
      setIsReset(false)
    },
    reset: () => {
      setIsReset(true)
    },
    isReset: () => {
      return isReset()
    },
  }
}

const QueryErrorResetBoundaryContext = createContext(createValue())

// HOOK

export const useQueryErrorResetBoundary = () =>
  useContext(QueryErrorResetBoundaryContext)

// COMPONENT

export interface QueryErrorResetBoundaryProps {
  children: ((value: QueryErrorResetBoundaryValue) => JSX.Element) | JSX.Element
}

export const QueryErrorResetBoundary = (
  props: QueryErrorResetBoundaryProps,
) => {
  const [value] = createSignal(createValue())
  return (
    <QueryErrorResetBoundaryContext.Provider value={value()}>
      {typeof props.children === 'function'
        ? (props.children as Function)(value())
        : props.children}
    </QueryErrorResetBoundaryContext.Provider>
  )
}

// packages/react-query/src/QueryErrorResetBoundary.tsx
import * as React from 'react'

// CONTEXT

export interface QueryErrorResetBoundaryValue {
  clearReset: () => void
  isReset: () => boolean
  reset: () => void
}

function createValue(): QueryErrorResetBoundaryValue {
  let isReset = false
  return {
    clearReset: () => {
      isReset = false
    },
    reset: () => {
      isReset = true
    },
    isReset: () => {
      return isReset
    },
  }
}

const QueryErrorResetBoundaryContext = React.createContext(createValue())

// HOOK

export const useQueryErrorResetBoundary = () =>
  React.useContext(QueryErrorResetBoundaryContext)

// COMPONENT

export interface QueryErrorResetBoundaryProps {
  children:
    | ((value: QueryErrorResetBoundaryValue) => React.ReactNode)
    | React.ReactNode
}

export const QueryErrorResetBoundary = ({
  children,
}: QueryErrorResetBoundaryProps) => {
  const [value] = React.useState(() => createValue())
  return (
    <QueryErrorResetBoundaryContext.Provider value={value}>
      {typeof children === 'function'
        ? (children as Function)(value)
        : children}
    </QueryErrorResetBoundaryContext.Provider>
  )
}
