// packages/qwik-query/src/useMutation.ts
import type { NoSerialize } from "@builder.io/qwik";
import {
  noSerialize,
  useSignal,
  useStore,
  useVisibleTask$,
} from "@builder.io/qwik";
import type { DefaultError } from "@tanstack/query-core";
import { MutationObserver, notifyManager } from "@tanstack/query-core";
import { createQueryClient } from "./useQueryClient";
import type { UseMutationOptions, UseMutationResult } from "./types";

export function useMutation<
  TData = unknown,
  TError = DefaultError,
  TVariables = void,
  TContext = unknown,
>(
  options: UseMutationOptions<TData, TError, TVariables, TContext>
): UseMutationResult<TData, TError, TVariables, TContext> & {
  options: UseMutationOptions<TData, TError, TVariables, TContext>;
};

export function useMutation(options: any /*UseMutationOptions*/ ): UseMutationResult & {
  options: UseMutationOptions;
} {
  const store = useStore<any>({});
  const observerSig = useSignal<NoSerialize<MutationObserver>>();

  useVisibleTask$(({ cleanup }) => {
    const { observer, unsubscribe } = createMutationObserver(store, options);
    observerSig.value = observer;

    cleanup(unsubscribe);
  });

  useVisibleTask$(({ track }) => {
    track(() => store.options);
    if (observerSig.value) {
      observerSig.value.setOptions(options);
    }
  });

  return store;
}

const createMutationObserver = (store: any, options: any) => {
  const client = createQueryClient();
  const observer = new MutationObserver(client, options);

  const unsubscribe = observer.subscribe(
    notifyManager.batchCalls((result: any) => {
      store.result = noSerialize(observer.getCurrentResult());
      store.mutateAsync = noSerialize(result.mutate);
    })
  );

  store.mutate = noSerialize((variables: any, mutateOptions: any) => {
    observer.mutate(variables, mutateOptions).catch(() => {});
  });

  return { observer: noSerialize(observer), unsubscribe };
};

// packages/react-query/src/useMutation.ts
'use client'
import * as React from 'react'
import { MutationObserver, notifyManager } from '@tanstack/query-core'
import { useQueryClient } from './QueryClientProvider'
import { noop, shouldThrowError } from './utils'
import type {
  UseMutateFunction,
  UseMutationOptions,
  UseMutationResult,
} from './types'
import type { DefaultError, QueryClient } from '@tanstack/query-core'

// HOOK

export function useMutation<
  TData = unknown,
  TError = DefaultError,
  TVariables = void,
  TContext = unknown,
>(
  options: UseMutationOptions<TData, TError, TVariables, TContext>,
  queryClient?: QueryClient,
): UseMutationResult<TData, TError, TVariables, TContext> {
  const client = useQueryClient(queryClient)

  const [observer] = React.useState(
    () =>
      new MutationObserver<TData, TError, TVariables, TContext>(
        client,
        options,
      ),
  )

  React.useEffect(() => {
    observer.setOptions(options)
  }, [observer, options])

  const result = React.useSyncExternalStore(
    React.useCallback(
      (onStoreChange) =>
        observer.subscribe(notifyManager.batchCalls(onStoreChange)),
      [observer],
    ),
    () => observer.getCurrentResult(),
    () => observer.getCurrentResult(),
  )

  const mutate = React.useCallback<
    UseMutateFunction<TData, TError, TVariables, TContext>
  >(
    (variables, mutateOptions) => {
      observer.mutate(variables, mutateOptions).catch(noop)
    },
    [observer],
  )

  if (
    result.error &&
    shouldThrowError(observer.options.throwOnError, [result.error])
  ) {
    throw result.error
  }

  return { ...result, mutate, mutateAsync: result.mutate }
}
