// examples/svelte/star-wars/src/routes/characters/+page.svelte
<script lang="ts">
  import { useQuery } from "@tanstack/svelte-query"

  const getCharacters = async () => {
    const res = await fetch("https://swapi.dev/api/people/");
    return await res.json();
  }

  const query = useQuery({
    queryKey: ["characters"],
    queryFn: getCharacters,
  });
</script>

{#if $query.status === "loading"}
    <p>Loading...</p>
{/if}

{#if $query.status === "error"}
    <p>Error :(</p>
{/if}

{#if $query.status === "success"}
  <div>
    <h2 class="text-4xl">Characters</h2>
    {#each $query.data.results as person}
      {@const personUrlParts = person.url.split("/").filter(Boolean)}
      {@const personId = personUrlParts[personUrlParts.length - 1]}
        <article>
          <a href={`/characters/${personId}`}>
            <h6 class="text-xl">{person.name}</h6>
          </a>
        </article>
    {/each}
  </div>
{/if}

// examples/react/star-wars/src/Characters.js
import React from "react";
import { Typography, Link } from "@material-ui/core";
import { Link as RouterLink } from "react-router-dom";
import { useQuery } from "@tanstack/react-query";
import fetch from "./fetch";

export default function Characters(props) {
  const { status, error, data } = useQuery(["characters"], () =>
    fetch(`https://swapi.dev/api/people/`)
  );

  if (status === "loading") return <p>Loading...</p>;
  if (status === "error") return <p>Error :(</p>;

  return (
    <div>
      <Typography variant="h2">Characters</Typography>
      {data.results.map((person) => {
        const personUrlParts = person.url.split("/").filter(Boolean);
        const personId = personUrlParts[personUrlParts.length - 1];
        return (
          <article key={personId} style={{ margin: "16px 0 0" }}>
            <Link component={RouterLink} to={`/characters/${personId}`}>
              <Typography variant="h6">{person.name}</Typography>
            </Link>
          </article>
        );
      })}
    </div>
  );
}
