// examples/svelte/star-wars/src/routes/films/+page.svelte
<script lang="ts">
  import { getFilms } from '$lib/api'
  import { createQuery } from '@tanstack/svelte-query'

  const query = createQuery(() => ({
    queryKey: ['films'],
    queryFn: () => getFilms(),
  }))
</script>

{#if query.status === 'pending'}
  <p>Loading...</p>
{/if}

{#if query.status === 'error'}
  <p>Error :(</p>
{/if}

{#if query.status === 'success'}
  <div>
    <h2 class="text-4xl">Films</h2>
    {#each query.data.results as film}
      {@const filmUrlParts = film.url.split('/').filter(Boolean)}
      {@const filmId = filmUrlParts[filmUrlParts.length - 1]}
      <article>
        <a class="text-blue-500 hover:underline" href={`/films/${filmId}`}>
          <h6 class="text-xl">
            {film.episode_id}. {film.title}{' '}
            <em>
              ({new Date(Date.parse(film.release_date)).getFullYear()})
            </em>
          </h6>
        </a>
      </article>
    {/each}
  </div>
{/if}

// examples/react/star-wars/src/Films.tsx
import { Link as RouterLink } from 'react-router-dom'
import { useQuery } from '@tanstack/react-query'
import { getFilms } from './api'

export default function Films() {
  const { data, status } = useQuery({
    queryKey: ['films'],
    queryFn: () => getFilms(),
  })

  if (status === 'pending') {
    return <p>Loading...</p>
  }
  if (status === 'error') {
    return <p>Error :(</p>
  }

  return (
    <div>
      <h2 className="text-4xl">Films</h2>
      {data.results.map((film: any) => {
        const filmUrlParts = film.url.split('/').filter(Boolean)
        const filmId = filmUrlParts[filmUrlParts.length - 1]
        return (
          <article key={filmId}>
            <RouterLink
              className="text-blue-500 hover:underline"
              to={`/films/${filmId}`}
            >
              <h6 className="text-xl">
                {film.episode_id}. {film.title}{' '}
                <em>
                  ({new Date(Date.parse(film.release_date)).getFullYear()})
                </em>
              </h6>
            </RouterLink>
          </article>
        )
      })}
    </div>
  )
}
