// packages/qwik-query/src/useIsFetching.ts
import type { QRL } from '@builder.io/qwik';
import { useSignal, useVisibleTask$ } from '@builder.io/qwik';
import {
	type Query,
	type QueryFilters,
	type QueryKey,
} from '@tanstack/query-core';
import { createQueryClient } from './useQueryClient';

export const useIsFetching = (
	filters?: QueryFilters & {
		predicate: QRL<
			() => (query: Query<unknown, Error, unknown, QueryKey>) => boolean
		>;
	}
) => {
	const isFetchingSig = useSignal<number>(0);

	useVisibleTask$(({ cleanup }) => {
		const client = createQueryClient();
		const cache = client.getQueryCache();
		isFetchingSig.value = client.isFetching(filters);
		const unsubscribe = cache.subscribe(() => {
			const newIsFetching = client.isFetching(filters);
			if (isFetchingSig.value !== newIsFetching) {
				isFetchingSig.value = newIsFetching;
			}
		});

		cleanup(unsubscribe);
	});

	return isFetchingSig;
};

// packages/angular-query-experimental/src/useIsFetching.ts
import {
  DestroyRef,
  assertInInjectionContext,
  inject,
  signal,
} from '@angular/core'
import {
  type QueryClient,
  type QueryFilters,
  notifyManager,
} from '@tanstack/query-core'
import { QueryClientService } from './QueryClientService'
import type { Signal } from '@angular/core'

export function useIsFetching(
  filters?: QueryFilters,
  queryClient?: QueryClient,
): Signal<number> {
  assertInInjectionContext(useIsFetching)

  const destroyRef = inject(DestroyRef)

  /** Load query client */
  if (!queryClient) {
    queryClient = inject(QueryClientService).useQueryClient()
  }
  const cache = queryClient.getQueryCache()
  // isFetching is the prev value initialized on mount *
  let isFetching = queryClient.isFetching(filters)

  const result = signal(isFetching)
  const unsubscribe = cache.subscribe(
    notifyManager.batchCalls(() => {
      const newIsFetching = queryClient!.isFetching(filters)
      if (isFetching !== newIsFetching) {
        // * and update with each change
        isFetching = newIsFetching
        result.set(isFetching)
      }
    }),
  )

  destroyRef.onDestroy(unsubscribe)
  return result
}
